// Api Action Types
export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE = 'API_RESPONSE';
export const API_ERROR = 'API_ERROR';
export const API_SUCCESS = 'API_SUCCESS';

// App Action Types
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const OPEN_CUSTOM_DIALOG = 'OPEN_CUSTOM_DIALOG';
export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

// Backoffice Action Types
export const CHANGE_CURRENT_LIST = 'CHANGE_CURRENT_LIST'
export const ALL_NEWS_SOURCES_RECEIVED = 'ALL_NEWS_SOURCES_RECEIVED';
export const WHITELIST_SITE_ADDED = 'WHITELIST_SITE_ADDED';
export const WHITELIST_SITE_REMOVED = 'WHITELIST_SITE_REMOVED';
export const BLACKLIST_SITE_ADDED = 'BLACKLIST_SITE_ADDED';
export const BLACKLIST_SITE_REMOVED = 'BLACKLIST_SITE_REMOVED';

//Auth Action Types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';