// Api Action Types
export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE = 'API_RESPONSE';

// App Action Types
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const OPEN_CUSTOM_DIALOG = 'OPEN_CUSTOM_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

// Backoffice Action Types
export const CHANGE_CURRENT_LIST = 'CHANGE_CURRENT_LIST'
export const ALL_NEWS_SOURCES_RECEIVED = 'ALL_NEWS_SOURCES_RECEIVED';
export const ADD_WHITELIST_SITE = 'ADD_WHITELIST_SITE';
export const REMOVE_WHITELIST_SITE = 'REMOVE_WHITELIST_SITE';
export const ADD_BLACKLIST_SITE = 'ADD_BLACKLIST_SITE';
export const REMOVE_BLACKLIST_SITE = 'REMOVE_BLACKLIST_SITE';