//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriThink.Client.Core.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CriThink.Client.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AboutViewModel_LogoutErrorOk {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutErrorOk", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_AccountSettings {
            get {
                return ResourceManager.GetString("AboutViewModel.AccountSettings", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_GetHelp {
            get {
                return ResourceManager.GetString("AboutViewModel.GetHelp", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_GiveFeedback {
            get {
                return ResourceManager.GetString("AboutViewModel.GiveFeedback", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_HowWorks {
            get {
                return ResourceManager.GetString("AboutViewModel.HowWorks", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_InviteFriends {
            get {
                return ResourceManager.GetString("AboutViewModel.InviteFriends", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Legal {
            get {
                return ResourceManager.GetString("AboutViewModel.Legal", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Logout {
            get {
                return ResourceManager.GetString("AboutViewModel.Logout", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_LogoutCancel {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutCancel", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_LogoutErrorMessage {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutErrorMessage", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_LogoutMessage {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutMessage", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_LogoutOk {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutOk", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Notifications {
            get {
                return ResourceManager.GetString("AboutViewModel.Notifications", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_PersonalInfo {
            get {
                return ResourceManager.GetString("AboutViewModel.PersonalInfo", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_PrivacySettings {
            get {
                return ResourceManager.GetString("AboutViewModel.PrivacySettings", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Referrals {
            get {
                return ResourceManager.GetString("AboutViewModel.Referrals", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Support {
            get {
                return ResourceManager.GetString("AboutViewModel.Support", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_ToS {
            get {
                return ResourceManager.GetString("AboutViewModel.ToS", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_Version {
            get {
                return ResourceManager.GetString("AboutViewModel.Version", resourceCulture);
            }
        }
        
        internal static string AboutViewModel_ViewProfile {
            get {
                return ResourceManager.GetString("AboutViewModel.ViewProfile", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_FormatErrorMessage {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.FormatErrorMessage", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_FormatErrorOk {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.FormatErrorOk", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_NewsLinkHint {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.NewsLinkHint", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_Title {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.Title", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_RecentSearch {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.RecentSearch", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_InsertEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.InsertEmail", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_RecoverPassword {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RecoverPassword", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_Send {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.Send", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_EmailHint {
            get {
                return ResourceManager.GetString("LoginViewModel.EmailHint", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_Facebook {
            get {
                return ResourceManager.GetString("LoginViewModel.Facebook", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginViewModel.ForgotPassword", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_Google {
            get {
                return ResourceManager.GetString("LoginViewModel.Google", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_Login {
            get {
                return ResourceManager.GetString("LoginViewModel.Login", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("LoginViewModel.PasswordHint", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_OrAccount {
            get {
                return ResourceManager.GetString("LoginViewModel.OrAccount", resourceCulture);
            }
        }
        
        internal static string NewsCheckerResultViewModel_ClassificationHeader {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.ClassificationHeader", resourceCulture);
            }
        }
        
        internal static string NewsCheckerResultViewModel_RelatedDNews {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.RelatedDNews", resourceCulture);
            }
        }
        
        internal static string NewsCheckerResultViewModel_UnknownClassificationHeader {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.UnknownClassificationHeader", resourceCulture);
            }
        }
        
        internal static string NewsCheckerResultViewModel_UnknownDescription {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.UnknownDescription", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_DebunkingNewsTitle {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.DebunkingNewsTitle", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_GoodAfternoon {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodAfternoon", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_GoodEvening {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodEvening", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_GoodMorning {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodMorning", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_GoodNight {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodNight", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_Motto {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.Motto", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_NewsLinkHint {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.NewsLinkHint", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_Hello {
            get {
                return ResourceManager.GetString("ProfileViewModel.Hello", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_ConfirmPasswordReset {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ConfirmPasswordReset", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_ErrorPasswordReset {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ErrorPasswordReset", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_InsertPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.InsertPassword", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_RepeatPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.RepeatPassword", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_ResetPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ResetPassword", resourceCulture);
            }
        }
        
        internal static string ResetPasswordViewModel_Send {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.Send", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_ConfirmErrorMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ConfirmErrorMessage", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_ConfirmWelcomeMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ConfirmWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_EmailHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.EmailHint", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_ErrorMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ErrorMessage", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.PasswordHint", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_RepeatPasswordHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.RepeatPasswordHint", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_SignUp {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.SignUp", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_UsernameHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.UsernameHint", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_WelcomeMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_AlreadyAccount {
            get {
                return ResourceManager.GetString("SignUpViewModel.AlreadyAccount", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_Facebook {
            get {
                return ResourceManager.GetString("SignUpViewModel.Facebook", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_Google {
            get {
                return ResourceManager.GetString("SignUpViewModel.Google", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_SignUpCaption {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpCaption", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_DialogOk {
            get {
                return ResourceManager.GetString("SignUpViewModel.DialogOk", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_DialogCancel {
            get {
                return ResourceManager.GetString("SignUpViewModel.DialogCancel", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_EmailHint {
            get {
                return ResourceManager.GetString("SignUpViewModel.EmailHint", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_SignUpEmail {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpEmail", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpTitle", resourceCulture);
            }
        }
        
        internal static string WelcomeLoginSignInViewModel_Login {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.Login", resourceCulture);
            }
        }
        
        internal static string WelcomeLoginSignInViewModel_Motto {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.Motto", resourceCulture);
            }
        }
        
        internal static string WelcomeLoginSignInViewModel_SignIn {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.SignIn", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_SeeAll {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.SeeAll", resourceCulture);
            }
        }
        
        internal static string DebunkingNewsListViewModel_Title {
            get {
                return ResourceManager.GetString("DebunkingNewsListViewModel.Title", resourceCulture);
            }
        }
        
        internal static string SpotFakeNewsHomeViewModel_ADescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.ADescription", resourceCulture);
            }
        }
        
        internal static string SpotFakeNewsHomeViewModel_DDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.DDescription", resourceCulture);
            }
        }
        
        internal static string SpotFakeNewsHomeViewModel_EDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.EDescription", resourceCulture);
            }
        }
        
        internal static string SpotFakeNewsHomeViewModel_HDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.HDescription", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_SocialLoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginViewModel.SocialLoginErrorMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_LoginErrorMessage {
            get {
                return ResourceManager.GetString("SignUpViewModel.LoginErrorMessage", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginViewModel.LoginErrorMessage", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_Pleasure {
            get {
                return ResourceManager.GetString("LoginViewModel.Pleasure", resourceCulture);
            }
        }
        
        internal static string LoginViewModel_WelcomeBack {
            get {
                return ResourceManager.GetString("LoginViewModel.WelcomeBack", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_SignUpEmailCaption {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.SignUpEmailCaption", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_SignUpEmailTitle {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.SignUpEmailTitle", resourceCulture);
            }
        }
        
        internal static string HomeViewModel_FormatErrorMessage {
            get {
                return ResourceManager.GetString("HomeViewModel.FormatErrorMessage", resourceCulture);
            }
        }
        
        internal static string HomeViewModel_FormatErrorOk {
            get {
                return ResourceManager.GetString("HomeViewModel.FormatErrorOk", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_RequestErrorMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RequestErrorMessage", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_RequestErrorOk {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RequestErrorOk", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_RequestMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RequestMessage", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordViewModel_RequestOk {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RequestOk", resourceCulture);
            }
        }
        
        internal static string CheckNewsViewModel_NewsSearch {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.NewsSearch", resourceCulture);
            }
        }
        
        internal static string SignUpEmailViewModel_SelectAvatar {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.SelectAvatar", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_RegisteredOn {
            get {
                return ResourceManager.GetString("ProfileViewModel.RegisteredOn", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_AboutTitle {
            get {
                return ResourceManager.GetString("ProfileViewModel.AboutTitle", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_MyProfile {
            get {
                return ResourceManager.GetString("ProfileViewModel.MyProfile", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_OpenApp {
            get {
                return ResourceManager.GetString("ProfileViewModel.OpenApp", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_MyBadges {
            get {
                return ResourceManager.GetString("ProfileViewModel.MyBadges", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_IAmGender {
            get {
                return ResourceManager.GetString("ProfileViewModel.IAmGender", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_IBornOn {
            get {
                return ResourceManager.GetString("ProfileViewModel.IBornOn", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_ILiveIn {
            get {
                return ResourceManager.GetString("ProfileViewModel.ILiveIn", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_MyNameIs {
            get {
                return ResourceManager.GetString("ProfileViewModel.MyNameIs", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Blog {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Blog", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Country {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Country", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Description {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Description", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_DoB {
            get {
                return ResourceManager.GetString("EditProfileViewModel.DoB", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Facebook {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Facebook", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_FamilyName {
            get {
                return ResourceManager.GetString("EditProfileViewModel.FamilyName", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Gender {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Gender", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_GivenName {
            get {
                return ResourceManager.GetString("EditProfileViewModel.GivenName", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Instagram {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Instagram", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Skype {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Skype", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Snapchat {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Snapchat", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Telegram {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Telegram", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Twitter {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Twitter", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_YouTube {
            get {
                return ResourceManager.GetString("EditProfileViewModel.YouTube", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Bio {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Bio", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Social {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Social", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_SaveProfile {
            get {
                return ResourceManager.GetString("EditProfileViewModel.SaveProfile", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_UpdateError {
            get {
                return ResourceManager.GetString("EditProfileViewModel.UpdateError", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_UpdateOk {
            get {
                return ResourceManager.GetString("EditProfileViewModel.UpdateOk", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_Female {
            get {
                return ResourceManager.GetString("GenderViewModel.Female", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_GenderFluid {
            get {
                return ResourceManager.GetString("GenderViewModel.GenderFluid", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_GenderNeutral {
            get {
                return ResourceManager.GetString("GenderViewModel.GenderNeutral", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_Male {
            get {
                return ResourceManager.GetString("GenderViewModel.Male", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_NoGender {
            get {
                return ResourceManager.GetString("GenderViewModel.NoGender", resourceCulture);
            }
        }
        
        internal static string GenderViewModel_NonBinary {
            get {
                return ResourceManager.GetString("GenderViewModel.NonBinary", resourceCulture);
            }
        }
        
        internal static string EditProfileViewModel_Cancel {
            get {
                return ResourceManager.GetString("EditProfileViewModel.Cancel", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DangerZone {
            get {
                return ResourceManager.GetString("ProfileViewModel.DangerZone", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_CloseAccount {
            get {
                return ResourceManager.GetString("ProfileViewModel.CloseAccount", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteErrorMessage {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteErrorMessage", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteErrorTitle {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteErrorTitle", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteTitle {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteTitle", resourceCulture);
            }
        }
        
        internal static string ProfileViewModel_DeleteMessage {
            get {
                return ResourceManager.GetString("ProfileViewModel.DeleteMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_OrAccount {
            get {
                return ResourceManager.GetString("SignUpViewModel.OrAccount", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccount {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccount", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountConfirmationMessage {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountConfirmationTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountConfirmationTitle", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountErrorMessage {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountErrorMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountErrorTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountErrorTitle", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountMessage {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountMessage", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_RestoreAccountTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.RestoreAccountTitle", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_MottoOne {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.MottoOne", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_MottoTwo {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.MottoTwo", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_ActiveUsers {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.ActiveUsers", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_TotalSearches {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.TotalSearches", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_UserSearches {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.UserSearches", resourceCulture);
            }
        }
        
        internal static string HomeStatisticsViewModel_Error {
            get {
                return ResourceManager.GetString("HomeStatisticsViewModel.Error", resourceCulture);
            }
        }
        
        internal static string NewsCheckerViewModel_Hello {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.Hello", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_DialogTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.DialogTitle", resourceCulture);
            }
        }
        
        internal static string SignUpViewModel_Login {
            get {
                return ResourceManager.GetString("SignUpViewModel.Login", resourceCulture);
            }
        }
    }
}
