//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriThink.Client.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CriThink.Client.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Debunking News.
        /// </summary>
        internal static string DebunkingNewsCollectionView_DebunkingNewsTitle {
            get {
                return ResourceManager.GetString("DebunkingNewsCollectionView.DebunkingNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip (DEBUG).
        /// </summary>
        internal static string LoginViewModel_Jump {
            get {
                return ResourceManager.GetString("LoginViewModel.Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodAfternoon {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodEvening {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodMorning {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodNight {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE THE HEAD TODAY.
        /// </summary>
        internal static string NewsCheckerViewModel_Motto {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which news do you want to check?.
        /// </summary>
        internal static string NewsCheckerViewModel_NewsLinkHint {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.NewsLinkHint", resourceCulture);
            }
        }
    }
}
