//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriThink.Client.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CriThink.Client.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Account settings.
        /// </summary>
        internal static string AboutViewModel_AccountSettings {
            get {
                return ResourceManager.GetString("AboutViewModel.AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Get help.
        /// </summary>
        internal static string AboutViewModel_GetHelp {
            get {
                return ResourceManager.GetString("AboutViewModel.GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Give us feedback.
        /// </summary>
        internal static string AboutViewModel_GiveFeedback {
            get {
                return ResourceManager.GetString("AboutViewModel.GiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How CriThink works.
        /// </summary>
        internal static string AboutViewModel_HowWorks {
            get {
                return ResourceManager.GetString("AboutViewModel.HowWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invite friends.
        /// </summary>
        internal static string AboutViewModel_InviteFriends {
            get {
                return ResourceManager.GetString("AboutViewModel.InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Legal.
        /// </summary>
        internal static string AboutViewModel_Legal {
            get {
                return ResourceManager.GetString("AboutViewModel.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log out.
        /// </summary>
        internal static string AboutViewModel_Logout {
            get {
                return ResourceManager.GetString("AboutViewModel.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string AboutViewModel_LogoutCancel {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry, you can&apos;t log out right now.
        /// </summary>
        internal static string AboutViewModel_LogoutErrorMessage {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        internal static string AboutViewModel_LogoutErrorOk {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutErrorOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to log out?.
        /// </summary>
        internal static string AboutViewModel_LogoutMessage {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log out.
        /// </summary>
        internal static string AboutViewModel_LogoutOk {
            get {
                return ResourceManager.GetString("AboutViewModel.LogoutOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notifications.
        /// </summary>
        internal static string AboutViewModel_Notifications {
            get {
                return ResourceManager.GetString("AboutViewModel.Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Personal information.
        /// </summary>
        internal static string AboutViewModel_PersonalInfo {
            get {
                return ResourceManager.GetString("AboutViewModel.PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy settings.
        /// </summary>
        internal static string AboutViewModel_PrivacySettings {
            get {
                return ResourceManager.GetString("AboutViewModel.PrivacySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Referrals.
        /// </summary>
        internal static string AboutViewModel_Referrals {
            get {
                return ResourceManager.GetString("AboutViewModel.Referrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Support.
        /// </summary>
        internal static string AboutViewModel_Support {
            get {
                return ResourceManager.GetString("AboutViewModel.Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Terms of Service.
        /// </summary>
        internal static string AboutViewModel_ToS {
            get {
                return ResourceManager.GetString("AboutViewModel.ToS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0}.
        /// </summary>
        internal static string AboutViewModel_Version {
            get {
                return ResourceManager.GetString("AboutViewModel.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show profile.
        /// </summary>
        internal static string AboutViewModel_ViewProfile {
            get {
                return ResourceManager.GetString("AboutViewModel.ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The link you inserted is not valid..
        /// </summary>
        internal static string CheckNewsViewModel_FormatErrorMessage {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.FormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        internal static string CheckNewsViewModel_FormatErrorOk {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.FormatErrorOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search here.
        /// </summary>
        internal static string CheckNewsViewModel_NewsLinkHint {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.NewsLinkHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recent search.
        /// </summary>
        internal static string CheckNewsViewModel_RecentSearch {
            get {
                return ResourceManager.GetString("CheckNewsViewModel.RecentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Debunking News.
        /// </summary>
        internal static string DebunkingNewsListViewModel_Title {
            get {
                return ResourceManager.GetString("DebunkingNewsListViewModel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert your email.
        /// </summary>
        internal static string ForgotPasswordViewModel_InsertEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.InsertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore your password.
        /// </summary>
        internal static string ForgotPasswordViewModel_RecoverPassword {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send.
        /// </summary>
        internal static string ForgotPasswordViewModel_Send {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email or username.
        /// </summary>
        internal static string LoginViewModel_EmailHint {
            get {
                return ResourceManager.GetString("LoginViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue with Facebook.
        /// </summary>
        internal static string LoginViewModel_Facebook {
            get {
                return ResourceManager.GetString("LoginViewModel.Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forgot password?.
        /// </summary>
        internal static string LoginViewModel_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginViewModel.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue with Google.
        /// </summary>
        internal static string LoginViewModel_Google {
            get {
                return ResourceManager.GetString("LoginViewModel.Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        internal static string LoginViewModel_Login {
            get {
                return ResourceManager.GetString("LoginViewModel.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        internal static string LoginViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("LoginViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You may also like...
        /// </summary>
        internal static string NewsCheckerResultDetailViewModel_RelatedDNews {
            get {
                return ResourceManager.GetString("NewsCheckerResultDetailViewModel.RelatedDNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We think this website is {0}.
        /// </summary>
        internal static string NewsCheckerResultViewModel_ClassificationHeader {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.ClassificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unfortunately we didn&apos;t know this website yet..
        /// </summary>
        internal static string NewsCheckerResultViewModel_UnknownClassificationHeader {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.UnknownClassificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We are going to investigate this website and we will send you back an email with the result as soon as possible! Thank you!.
        /// </summary>
        internal static string NewsCheckerResultViewModel_UnknownDescription {
            get {
                return ResourceManager.GetString("NewsCheckerResultViewModel.UnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Latest Debunking News.
        /// </summary>
        internal static string NewsCheckerViewModel_DebunkingNewsTitle {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.DebunkingNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good afternoon.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodAfternoon {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good evening.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodEvening {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good morning.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodMorning {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Good night.
        /// </summary>
        internal static string NewsCheckerViewModel_GoodNight {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a USE THE HEAD TODAY.
        /// </summary>
        internal static string NewsCheckerViewModel_Motto {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Which news do you want to check?.
        /// </summary>
        internal static string NewsCheckerViewModel_NewsLinkHint {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.NewsLinkHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View all.
        /// </summary>
        internal static string NewsCheckerViewModel_SeeAll {
            get {
                return ResourceManager.GetString("NewsCheckerViewModel.SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hi, I&apos;m {0}.
        /// </summary>
        internal static string ProfileViewModel_Hello {
            get {
                return ResourceManager.GetString("ProfileViewModel.Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read the news.
        /// </summary>
        internal static string RelatedDebunkingNewsViewModel_OpenNews {
            get {
                return ResourceManager.GetString("RelatedDebunkingNewsViewModel.OpenNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hey {0}, you have successfully reset your password.
        /// </summary>
        internal static string ResetPasswordViewModel_ConfirmPasswordReset {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ConfirmPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry, we can&apos;t reset your password right now.
        /// </summary>
        internal static string ResetPasswordViewModel_ErrorPasswordReset {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ErrorPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert your new password.
        /// </summary>
        internal static string ResetPasswordViewModel_InsertPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.InsertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Repeat the new password.
        /// </summary>
        internal static string ResetPasswordViewModel_RepeatPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert a new password.
        /// </summary>
        internal static string ResetPasswordViewModel_ResetPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send.
        /// </summary>
        internal static string ResetPasswordViewModel_Send {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry but we can&apos;t confirm your email right now.
        /// </summary>
        internal static string SignUpEmailViewModel_ConfirmErrorMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hello {0}! You can now login.
        /// </summary>
        internal static string SignUpEmailViewModel_ConfirmWelcomeMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ConfirmWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        internal static string SignUpEmailViewModel_EmailHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry but we can&apos;t complete the sign up now.
        /// </summary>
        internal static string SignUpEmailViewModel_ErrorMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        internal static string SignUpEmailViewModel_PasswordHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Repeat Password.
        /// </summary>
        internal static string SignUpEmailViewModel_RepeatPasswordHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.RepeatPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Join Us!.
        /// </summary>
        internal static string SignUpEmailViewModel_SignUp {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username.
        /// </summary>
        internal static string SignUpEmailViewModel_UsernameHint {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.UsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Thank you for joining us! We sent you an email with a confirmation link. Please click on that link and perform the login.
        /// </summary>
        internal static string SignUpEmailViewModel_WelcomeMessage {
            get {
                return ResourceManager.GetString("SignUpEmailViewModel.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Already have an account?.
        /// </summary>
        internal static string SignUpViewModel_AlreadyAccount {
            get {
                return ResourceManager.GetString("SignUpViewModel.AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SignUp with Facebook.
        /// </summary>
        internal static string SignUpViewModel_Facebook {
            get {
                return ResourceManager.GetString("SignUpViewModel.Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SignUp with Google.
        /// </summary>
        internal static string SignUpViewModel_Google {
            get {
                return ResourceManager.GetString("SignUpViewModel.Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        internal static string SignUpViewModel_Login {
            get {
                return ResourceManager.GetString("SignUpViewModel.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It&apos;s easier to sign up now.
        /// </summary>
        internal static string SignUpViewModel_SignUpCaption {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SignUp with Email.
        /// </summary>
        internal static string SignUpViewModel_SignUpEmail {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Join Us.
        /// </summary>
        internal static string SignUpViewModel_SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpViewModel.SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ccuracy: is the text of the article accurate? Sometimes grammatical errors might mean the information is not accurate..
        /// </summary>
        internal static string SpotFakeNewsHomeViewModel_ADescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.ADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a eceiving artefacts: does the article contain any image or video? Check for the originality of such artefacts as they can be manipulated or show an unrelated event or place..
        /// </summary>
        internal static string SpotFakeNewsHomeViewModel_DDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.DDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a vidence: does the author of the article present Evidence to support that particular point of view?.
        /// </summary>
        internal static string SpotFakeNewsHomeViewModel_EDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.EDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a eadlines do not contain the full story. Have you read the entire article?.
        /// </summary>
        internal static string SpotFakeNewsHomeViewModel_HDescription {
            get {
                return ResourceManager.GetString("SpotFakeNewsHomeViewModel.HDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        internal static string WelcomeLoginSignInViewModel_Login {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use the HEAD!.
        /// </summary>
        internal static string WelcomeLoginSignInViewModel_Motto {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign In.
        /// </summary>
        internal static string WelcomeLoginSignInViewModel_SignIn {
            get {
                return ResourceManager.GetString("WelcomeLoginSignInViewModel.SignIn", resourceCulture);
            }
        }
    }
}
