name: crithink_deploy

on:
  workflow_call:
    inputs:

      environment:
        required: true
        type: string
        description: 'Environment to deploy. Possible values are staging and production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: test
        run: echo "Env is ${{ inputs.environment }}"