name: staging_server_publish

env:
  ASPNETCORE_ENVIRONMENT: Staging
  TF_ENVIRONMENT: staging
  TF_VERSION: 1.1.9

on:
  push:
    paths:
      - src/CriThink.Server/**
      - terraform/**
      - .github/workflows/**
    branches: [feature/iac-azure] # TODO: change back to main

jobs:

  terraform_backend_deploy:
    uses: ./.github/workflows/terraform_backend_deploy.yml
    name: Terraform Backend Deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  terraform_global_deploy:
    uses: ./.github/workflows/terraform_global_deploy.yml
    name: Terraform Global Deploy
    needs: terraform_backend_deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  test:
    runs-on: ubuntu-latest
    needs: terraform_global_deploy
    steps:
      - name: print
        run: |
          echo ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_name.value}}

  terraform_environment_deploy:
    uses: ./.github/workflows/terraform_environment_deploy.yml
    name: Terraform Environment Deploy
    needs: terraform_global_deploy
    secrets: inherit
    with:
      tf_version: 1.1.9
      tf_environment: staging
      acr_name: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_name.value}}