name: staging_server_publish

env:
  ASPNETCORE_ENVIRONMENT: Staging
  TF_ENVIRONMENT: staging
  TF_VERSION: 1.1.9

on:
  push:
    paths:
      - src/CriThink.Server/**
      - terraform/**
      - .github/workflows/**
    branches: [feature/iac-azure] # TODO: change back to main

jobs:
  terraform_backend_deploy:
    uses: ./.github/workflows/terraform_backend_deploy.yml
    name: Terraform Backend Deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  terraform_global_deploy:
    uses: ./.github/workflows/terraform_global_deploy.yml
    name: Terraform Global Deploy
    needs: terraform_backend_deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  test:
    runs-on: ubuntu-latest
    needs: terraform_global_deploy
    steps:
      - name: print
        run: |
          echo ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_id.value}}

  terraform_environment_deploy:
    uses: ./.github/workflows/terraform_environment_deploy.yml
    name: Terraform Environment Deploy
    needs: terraform_global_deploy
    secrets: inherit
    with:
      tf_version: 1.1.9
      tf_environment: staging
      acr_name: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_name.value}}
      acr_user_password: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_admin_password.value}}
      acr_id: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_id.value}}
      db_admin_username: boss
      db_admin_password: king2Pac!
      db_name: demodb01
      db_server_name: crithink-demosql01
      objectid_app: f88cd778-ec64-4125-b066-94e99ddaa42c
      cognitive_account_name: crithinkstgcognitive01
      redis_name: crithink-demo-redis
      ai_name: stgai01
      internal_stg_name: crithinkintstgstg01
      app_domain: crithinkdemo.com
      keyvault_name: crithinkstgkeyvault01
      appsrvpln_name: demoplan01
      appsrv_name: crithink-demo
      jwt_secret_key: YylZ9OPQiIrLhgMvxWFA
      cross_service_scraper_value: scraper
      cross_service_dnews_value: vDEb&x2YMECb9@Qk9
      authentication_google_client_secret: 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
      authentication_google_client_id: 1064440290860-58nb9a9tbimmocjr6mkc4i3ah4cakp3f.apps.googleusercontent.com
      authentication_facebook_client_secret: "97d6403203028d136ec85bd7349207f3"
      authentication_facebook_client_id: "804449043690413"
      sendgrid_api_key: "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"
