name: staging_server_publish
on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/CriThink.sln
    - name: Build
      run: dotnet build src/CriThink.sln -c Release --no-restore 
    - name: Publish
      run: |
        dotnet publish src/CriThink.Server/CriThink.Server.Web/CriThink.Server.Web.csproj -c Release -o staging_crithink_server
