name: staging_server_publish

env:
  ASPNETCORE_ENVIRONMENT: Staging

on:
  push:
    paths:
      - src/CriThink.Server/**
      - terraform/**
      - .github/workflows/**
    branches: [feature/iac-azure] # TODO: change back to main

jobs:
  terraform_backend_deploy:
    uses: ./.github/workflows/terraform_backend_deploy.yml
    name: Terraform Backend Deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  terraform_global_deploy:
    uses: ./.github/workflows/terraform_global_deploy.yml
    name: Terraform Global Deploy
    needs: terraform_backend_deploy
    secrets: inherit
    with:
      tf_version: 1.1.9

  test:
    runs-on: ubuntu-latest
    needs: terraform_global_deploy
    steps:
      - name: print
        run: |
          echo ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_id.value}}

  terraform_environment_deploy:
    uses: ./.github/workflows/terraform_environment_deploy.yml
    name: Terraform Environment Deploy
    needs: terraform_global_deploy
    with:
      tf_version: 1.1.9
      tf_environment: staging
      acr_name: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_name.value}}
      acr_user_password: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_admin_password.value}}
      acr_id: ${{fromJson(needs.terraform_global_deploy.outputs.terraform_outputs).global_acr_id.value}}
      db_name: demodb01
      db_server_name: crithink-demosql01
      cognitive_account_name: crithinkstgcognitive01
      redis_name: crithink-demo-redis
      ai_name: stgai01
      internal_stg_name: crithinkintstgstg01
      app_domain: crithinkdemo.com
      keyvault_name: crithinkstgkeyvault01
      appsrvpln_name: demoplan01
      appsrv_name: crithink-demo
      authentication_google_client_id: 1064440290860-58nb9a9tbimmocjr6mkc4i3ah4cakp3f.apps.googleusercontent.com
      authentication_facebook_client_id: "804449043690413"
    secrets:
      db_admin_username: ${{ secrets.STG_DB_ADMIN_USERNAME }}
      db_admin_password: ${{ secrets.STG_DB_ADMIN_PASSWORD }}
      objectid_app: ${{ secrets.STG_OBJECTID_APP }}
      jwt_secret_key: ${{ secrets.STG_JWT_SECRET_KEY }}
      cross_service_dnews_value: ${{ secrets.STG_CROSS_SERVICE_DNEWS_VALUE }}
      cross_service_scraper_value: ${{ secrets.STG_CROSS_SERVICE_SCRAPER_VALUE }}
      authentication_google_client_secret: ${{ secrets.STG_GOOGLE_CLIENT_SECRET }}
      authentication_facebook_client_secret: ${{ secrets.STG_FACEBOOK_CLIENT_SECRET }}
      sendgrid_api_key: ${{ secrets.STG_SENDGRID_API_KEY }}

